### ISSUE TITLE
Event dispatch

### ISSUE THREAD

**Issue by CMCDragonkai** [nipuntalukdar/geeteventbus#1]
When an event is dispatched and the registered handlers are executed, how exactly are they executed? Are they executed on a separate Python thread, or separate Python process, or within the same thread that dispatched the event?

I have a situation where the thread which registers the handler, may actually be blocking on reading from a socket, so I'm confused as to how geeteventbus would execute the handler, given that the thread which registers the handler will be blocked on IO.

**Comment by nipuntalukdar** [comment]
The events are executed on different Python threads (not in different processes) by default (as the eventbus is asynchronous by default). In case we use synchronous eventbus, an event is executed on the same thread which submitted the event.

The thread registering the handler will not execute the events in case of asynchronous (default) eventbus, and in case of synchronous eventbus also the event will be executed from the registering thread only when the registering thread itself is submitting the events as well.

So, I don't think you should get any problem because the registering thread may block on something.

**Comment by CMCDragonkai** [comment]
Cool. I'm guessing this is the bag of handlers pattern rather than the queue to queue pattern then? (For reference, see: http://stackoverflow.com/questions/1092531/event-system-in-python)

**Comment by nipuntalukdar** [comment]
Somewhat like that, but not exactly same.
